
import { Product, User, UserRole } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    vendorId: 'v1',
    name: 'NeoStream Pro Headphones',
    description: 'High-fidelity wireless headphones with active noise cancellation and 40-hour battery life.',
    price: 299.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800&auto=format&fit=crop',
    stock: 15,
    rating: 4.8,
    reviews: []
  },
  {
    id: 'p2',
    vendorId: 'v2',
    name: 'Artisan Leather Weekender',
    description: 'Handcrafted full-grain leather bag perfect for short trips and professional travel.',
    price: 185.00,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1547949003-9792a18a2601?q=80&w=800&auto=format&fit=crop',
    stock: 8,
    rating: 4.5,
    reviews: []
  },
  {
    id: 'p3',
    vendorId: 'v1',
    name: 'SmartFlow Mesh Router',
    description: 'Next-gen Wi-Fi 6 coverage for homes up to 5000 sq ft. Low latency for gaming.',
    price: 149.50,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=800&auto=format&fit=crop',
    stock: 25,
    rating: 4.2,
    reviews: []
  },
  {
    id: 'p4',
    vendorId: 'v3',
    name: 'Organic Bamboo Sheets',
    description: 'Eco-friendly, hypoallergenic sheets with a silky smooth feel. 100% organic bamboo fibers.',
    price: 89.00,
    category: 'Home & Living',
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=80&w=800&auto=format&fit=crop',
    stock: 50,
    rating: 4.9,
    reviews: []
  },
  {
    id: 'p5',
    vendorId: 'v1',
    name: 'MechKey RGB Keyboard',
    description: 'Tactile mechanical switches with customizable per-key RGB lighting and aluminum frame.',
    price: 129.99,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?q=80&w=800&auto=format&fit=crop',
    stock: 12,
    rating: 4.7,
    reviews: []
  },
  {
    id: 'p6',
    vendorId: 'v2',
    name: 'Urban Explorer Parka',
    description: 'Water-resistant, insulated parka designed for sub-zero temperatures and city style.',
    price: 245.00,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?q=80&w=800&auto=format&fit=crop',
    stock: 5,
    rating: 4.6,
    reviews: []
  },
  {
    id: 'p7',
    vendorId: 'v3',
    name: 'Minimalist Ceramic Vase',
    description: 'Hand-thrown ceramic vase with a matte finish. Perfect for modern interior decor.',
    price: 45.00,
    category: 'Home & Living',
    image: 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?q=80&w=800&auto=format&fit=crop',
    stock: 20,
    rating: 4.4,
    reviews: []
  },
  {
    id: 'p8',
    vendorId: 'v1',
    name: 'Titan Smart Watch',
    description: 'Health tracking, GPS, and 7-day battery life in a sleek titanium casing.',
    price: 399.00,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=800&auto=format&fit=crop',
    stock: 18,
    rating: 4.9,
    reviews: []
  },
  {
    id: 'p9',
    vendorId: 'v2',
    name: 'Heritage Denim Jacket',
    description: 'Classic fit denim jacket made with 14oz Japanese selvedge denim.',
    price: 120.00,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1551537482-f2075a1d41f2?q=80&w=800&auto=format&fit=crop',
    stock: 10,
    rating: 4.5,
    reviews: []
  },
  {
    id: 'p10',
    vendorId: 'v3',
    name: 'Velvet Accent Chair',
    description: 'Luxurious emerald velvet chair with gold-finished steel legs for any living space.',
    price: 320.00,
    category: 'Home & Living',
    image: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?q=80&w=800&auto=format&fit=crop',
    stock: 3,
    rating: 4.8,
    reviews: []
  },
  {
    id: 'p11',
    vendorId: 'v4',
    name: 'PureZen Yoga Mat',
    description: 'Extra thick, non-slip eco-friendly rubber mat for ultimate joint support.',
    price: 65.00,
    category: 'Wellness',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=800&auto=format&fit=crop',
    stock: 40,
    rating: 4.7,
    reviews: []
  },
  {
    id: 'p12',
    vendorId: 'v4',
    name: 'Recovery Massage Gun',
    description: 'Percussive therapy device with 5 speeds and 4 interchangeable heads.',
    price: 150.00,
    category: 'Wellness',
    image: 'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?q=80&w=800&auto=format&fit=crop',
    stock: 15,
    rating: 4.5,
    reviews: []
  },
  {
    id: 'p13',
    vendorId: 'v5',
    name: 'Peak Performance Boots',
    description: 'Lightweight hiking boots with Vibram soles and Gore-Tex waterproofing.',
    price: 180.00,
    category: 'Outdoor',
    image: 'https://images.unsplash.com/photo-1520639889410-d04196f73203?q=80&w=800&auto=format&fit=crop',
    stock: 22,
    rating: 4.9,
    reviews: []
  },
  {
    id: 'p14',
    vendorId: 'v5',
    name: 'Solar Power Backpack',
    description: 'Built-in solar panels to charge your devices on the go. 30L capacity.',
    price: 115.00,
    category: 'Outdoor',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=800&auto=format&fit=crop',
    stock: 12,
    rating: 4.3,
    reviews: []
  },
  {
    id: 'p15',
    vendorId: 'v1',
    name: 'Lumix Mirrorless Camera',
    description: '4K video, 20.3MP sensor, and dual image stabilization for pro creators.',
    price: 1200.00,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=800&auto=format&fit=crop',
    stock: 4,
    rating: 4.8,
    reviews: []
  },
  {
    id: 'p16',
    vendorId: 'v2',
    name: 'Polarized Aviators',
    description: 'Handcrafted acetate frames with polarized lenses for 100% UV protection.',
    price: 145.00,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?q=80&w=800&auto=format&fit=crop',
    stock: 30,
    rating: 4.6,
    reviews: []
  },
  {
    id: 'p17',
    vendorId: 'v3',
    name: 'Espresso Maker Pro',
    description: '15-bar pressure pump and integrated milk frother for barista-quality coffee.',
    price: 450.00,
    category: 'Home & Living',
    image: 'https://images.unsplash.com/photo-1534040385115-33dcb3acba5b?q=80&w=800&auto=format&fit=crop',
    stock: 7,
    rating: 4.7,
    reviews: []
  },
  {
    id: 'p18',
    vendorId: 'v1',
    name: 'UltraPort Hub 7-in-1',
    description: 'Aluminum USB-C hub with 4K HDMI, SD card reader, and 100W power delivery.',
    price: 59.00,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1562975034-4537c35f0f35?q=80&w=800&auto=format&fit=crop',
    stock: 45,
    rating: 4.5,
    reviews: []
  },
  {
    id: 'p19',
    vendorId: 'v2',
    name: 'Cashmere Beanie',
    description: 'Ultra-soft 100% Mongolian cashmere beanie for ultimate warmth and comfort.',
    price: 75.00,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1521369909029-2afed882baee?q=80&w=800&auto=format&fit=crop',
    stock: 25,
    rating: 4.8,
    reviews: []
  },
  {
    id: 'p20',
    vendorId: 'v3',
    name: 'Smart Air Purifier',
    description: 'HEPA filter removes 99.97% of particles. App-controlled with air quality sensors.',
    price: 199.00,
    category: 'Home & Living',
    image: 'https://images.unsplash.com/photo-1585771724684-2626efec5315?q=80&w=800&auto=format&fit=crop',
    stock: 15,
    rating: 4.6,
    reviews: []
  },
  {
    id: 'p21',
    vendorId: 'v4',
    name: 'Eco-Glass Water Bottle',
    description: 'Borosilicate glass bottle with a protective silicone sleeve and bamboo lid.',
    price: 32.00,
    category: 'Wellness',
    image: 'https://images.unsplash.com/photo-1602143393494-1116f73801f6?q=80&w=800&auto=format&fit=crop',
    stock: 60,
    rating: 4.4,
    reviews: []
  },
  {
    id: 'p22',
    vendorId: 'v5',
    name: 'Portable Camping Grill',
    description: 'Stainless steel foldable grill. Compact design for backpacking and picnics.',
    price: 85.00,
    category: 'Outdoor',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?q=80&w=800&auto=format&fit=crop',
    stock: 20,
    rating: 4.5,
    reviews: []
  },
  {
    id: 'p23',
    vendorId: 'v1',
    name: 'Aura Bluetooth Speaker',
    description: '360-degree immersive sound with synchronized ambient light shows.',
    price: 135.00,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?q=80&w=800&auto=format&fit=crop',
    stock: 35,
    rating: 4.7,
    reviews: []
  },
  {
    id: 'p24',
    vendorId: 'v2',
    name: 'Silk Evening Wrap',
    description: 'Exquisite mulberry silk wrap with hand-rolled edges. A timeless accessory.',
    price: 95.00,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1618354691792-d1d42acfd860?q=80&w=800&auto=format&fit=crop',
    stock: 12,
    rating: 4.9,
    reviews: []
  },
  {
    id: 'p25',
    vendorId: 'v3',
    name: 'Memory Foam Pillow',
    description: 'Contoured cooling gel memory foam pillow for neck pain relief and better sleep.',
    price: 68.00,
    category: 'Home & Living',
    image: 'https://images.unsplash.com/photo-1629949009765-40f74d96ca11?q=80&w=800&auto=format&fit=crop',
    stock: 30,
    rating: 4.6,
    reviews: []
  },
  {
    id: 'p26',
    vendorId: 'v1',
    name: 'Nano SSD 2TB',
    description: 'Pocket-sized external drive with read speeds up to 2000MB/s.',
    price: 210.00,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1597740985671-2a8a3b80ec0f?q=80&w=800&auto=format&fit=crop',
    stock: 20,
    rating: 4.8,
    reviews: []
  },
  {
    id: 'p27',
    vendorId: 'v2',
    name: 'Chelsea Suede Boots',
    description: 'Italian suede boots with elastic side panels and durable rubber soles.',
    price: 165.00,
    category: 'Fashion',
    image: 'https://images.unsplash.com/photo-1638247025967-b4e38f787b76?q=80&w=800&auto=format&fit=crop',
    stock: 14,
    rating: 4.5,
    reviews: []
  },
  {
    id: 'p28',
    vendorId: 'v3',
    name: 'Digital Air Fryer',
    description: '6-quart capacity with 10 presets. Fry, roast, and bake with 85% less oil.',
    price: 125.00,
    category: 'Home & Living',
    image: 'https://images.unsplash.com/photo-1626071466175-79679659d839?q=80&w=800&auto=format&fit=crop',
    stock: 18,
    rating: 4.7,
    reviews: []
  },
  {
    id: 'p29',
    vendorId: 'v4',
    name: 'Vitamin Booster Serum',
    description: 'Potent Vitamin C and Hyaluronic acid serum for bright, youthful skin.',
    price: 48.00,
    category: 'Wellness',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=800&auto=format&fit=crop',
    stock: 50,
    rating: 4.8,
    reviews: []
  },
  {
    id: 'p30',
    vendorId: 'v5',
    name: 'Adjustable Dumbbell Set',
    description: 'Space-saving design that replaces 5 pairs of weights. Up to 25lbs each.',
    price: 195.00,
    category: 'Wellness',
    image: 'https://images.unsplash.com/photo-1638536532686-d610adfc8e5c?q=80&w=800&auto=format&fit=crop',
    stock: 8,
    rating: 4.6,
    reviews: []
  },
  {
    id: 'p31',
    vendorId: 'v1',
    name: 'Quantum VR Headset',
    description: 'All-in-one VR with 120Hz refresh rate and spatial audio tracking.',
    price: 499.00,
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?q=80&w=800&auto=format&fit=crop',
    stock: 10,
    rating: 4.9,
    reviews: []
  }
];

export const MOCK_USER: User = {
  id: 'u1',
  name: 'Alex Johnson',
  email: 'alex@example.com',
  role: UserRole.VENDOR,
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex'
};
